In [1]:
import time
from random import randint
from warnings import warn

import pandas as pd
import requests
from IPython.core.display import clear_output
from bs4 import BeautifulSoup

In [17]:
# Create dictinary to store various aspects of IMDB movie data
names = []
genres = []
durations = []
years = []
ratings = []
metascores = []
votes = []
total_gross = []
urls = []

# Monitor time
request = 1
movie_no = 1

for i in range(0, 1):
    
    # Url
    url = "https://www.imdb.com/list/ls055592025/?sort=num_votes,desc&st_dt=&mode=detail&page=1&ref_=ttls_vm_dtl," \
          "desc&start={}&ref_=adv_nxt".format(page)

    # Send the request and Get the response
    response = requests.get(url)

    # Make Soup
    soup = BeautifulSoup(response.text, "html.parser")

    # Fetch the data
    lister_items = soup.find_all("div", class_="lister-item")

    # Get the data
    for single_item in lister_items:
        single_item_content = single_item.find("div", class_="lister-item-content")

        # Extract the data
        # Movie Name
        name = single_item_content.h3.a.get_text()
        
        #Genre
        try:
            genre = single_item_content.find("span", class_="genre").get_text().replace("\n", "").rstrip()
        except:
            pass

        # Movie Time
        duration = single_item_content.find("p", class_="text-muted").find("span", class_="runtime")
        if duration is not None:
            duration = duration.get_text()
        else:
            duration = "0"
        
        # Year the movie has been released
        year = single_item_content.h3.find("span", class_="lister-item-year").get_text()
        
        # Movie ratings by users
        rating = single_item_content.find("span", class_="ipl-rating-star__rating").get_text()
        
        # Metascore-> Average of critic ratings
        metascore = single_item_content.find("div", class_="ratings-metascore")
        if metascore is not None:
            metascore = metascore.span.get_text()
        else:
            metascore = "0"
            
        # Number of reviews/votes for the movie
        vote_gross = single_item_content.find("span",{"name": "nv"}).get_text()

        try:
            gross = single_item_content.find('span', text='Gross:').find_next('span')['data-value']
        except:
            pass
        
        #Obtaining the url for each movie page
        url = "https://www.imdb.com"+single_item_content.a.get('href')
        
        # Add data to global array
        names.append(name)
        genres.append(genre)
        durations.append(duration)
        years.append(year)
        ratings.append(rating)
        metascores.append(metascore)
        votes.append(vote_gross)
        total_gross.append(gross)
        urls.append(url)
        
        print("Movie No. #{}: {} added!".format(movie_no, name))

        # Separate Every Movie
        print("---------------------------------------------------")

        # Increment Movie
        movie_no += 1

    # If status is not 200 then show an warning with request number
    if response.status_code != 200:
        warn("{} no. has status code {}\n{}\n".format(request, response.status_code, url))

    # Increment Request
    request += 1

    # Sleep for sometime
    print("\n---------------------------------------------------")
    rand_sec = randint(1, 30)
    time.sleep(rand_sec)
    print("\tSleep For {}sec".format(rand_sec))
    print("---------------------------------------------------\n")
    clear_output(wait=True)

# Store the data to csv format
data_frame = pd.DataFrame({
    "Name": names,
    "Genre":genres,
    "Year": years,
    "Duration": durations,
    "User Ratings": ratings,
    "Critic Score": metascores,
    "Vote": votes,
    "Gross": total_gross,
    'URL':urls
})

Movie No. #1: The Shawshank Redemption added!
---------------------------------------------------
Movie No. #2: Forrest Gump added!
---------------------------------------------------
Movie No. #3: Pulp Fiction added!
---------------------------------------------------
Movie No. #4: The Lord of the Rings: The Return of the King added!
---------------------------------------------------
Movie No. #5: The Godfather added!
---------------------------------------------------
Movie No. #6: Gladiator added!
---------------------------------------------------
Movie No. #7: The Silence of the Lambs added!
---------------------------------------------------
Movie No. #8: Saving Private Ryan added!
---------------------------------------------------
Movie No. #9: Star Wars added!
---------------------------------------------------
Movie No. #10: Schindler's List added!
---------------------------------------------------
Movie No. #11: The Green Mile added!
---------------------------------------------------
Movie No. #12: The Godfather: Part II added!
---------------------------------------------------
Movie No. #13: Titanic added!
---------------------------------------------------
Movie No. #14: Goodfellas added!
---------------------------------------------------
Movie No. #15: Braveheart added!
---------------------------------------------------
Movie No. #16: One Flew Over the Cuckoo's Nest added!
---------------------------------------------------
Movie No. #17: Indiana Jones and the Raiders of the Lost Ark added!
---------------------------------------------------
Movie No. #18: Jurassic Park added!
---------------------------------------------------
Movie No. #19: Good Will Hunting added!
---------------------------------------------------
Movie No. #20: A Clockwork Orange added!
---------------------------------------------------
Movie No. #21: The Pianist added!
---------------------------------------------------
Movie No. #22: Taxi Driver added!
---------------------------------------------------
Movie No. #23: 12 Angry Men added!
---------------------------------------------------
Movie No. #24: The Good, the Bad and the Ugly added!
---------------------------------------------------
Movie No. #25: Fargo added!
---------------------------------------------------
Movie No. #26: Psycho added!
---------------------------------------------------
Movie No. #27: 2001: A Space Odyssey added!
---------------------------------------------------
Movie No. #28: Apocalypse Now added!
---------------------------------------------------
Movie No. #29: Jaws added!
---------------------------------------------------
Movie No. #30: Casablanca added!
---------------------------------------------------
Movie No. #31: Rocky added!
---------------------------------------------------
Movie No. #32: Rain Man added!
---------------------------------------------------
Movie No. #33: Rear Window added!
---------------------------------------------------
Movie No. #34: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb added!
---------------------------------------------------
Movie No. #35: It's a Wonderful Life added!
---------------------------------------------------
Movie No. #36: Citizen Kane added!
---------------------------------------------------
Movie No. #37: Platoon added!
---------------------------------------------------
Movie No. #38: Unforgiven added!
---------------------------------------------------
Movie No. #39: E.T. the Extra-Terrestrial added!
---------------------------------------------------
Movie No. #40: Vertigo added!
---------------------------------------------------
Movie No. #41: Amadeus added!
---------------------------------------------------
Movie No. #42: The Exorcist added!
---------------------------------------------------
Movie No. #43: The Wizard of Oz added!
---------------------------------------------------
Movie No. #44: Raging Bull added!
---------------------------------------------------
Movie No. #45: The Deer Hunter added!
---------------------------------------------------
Movie No. #46: North by Northwest added!
---------------------------------------------------
Movie No. #47: Chinatown added!
---------------------------------------------------
Movie No. #48: To Kill a Mockingbird added!
---------------------------------------------------
Movie No. #49: Gone with the Wind added!
---------------------------------------------------
Movie No. #50: Lawrence of Arabia added!
---------------------------------------------------
Movie No. #51: The Graduate added!
---------------------------------------------------
Movie No. #52: Annie Hall added!
---------------------------------------------------
Movie No. #53: Some Like It Hot added!
---------------------------------------------------
Movie No. #54: Dances with Wolves added!
---------------------------------------------------
Movie No. #55: Singin' in the Rain added!
---------------------------------------------------
Movie No. #56: Ben-Hur added!
---------------------------------------------------
Movie No. #57: The Sound of Music added!
---------------------------------------------------
Movie No. #58: The Great Dictator added!
---------------------------------------------------
Movie No. #59: Sunset Blvd. added!
---------------------------------------------------
Movie No. #60: The Bridge on the River Kwai added!
---------------------------------------------------
Movie No. #61: Butch Cassidy and the Sundance Kid added!
---------------------------------------------------
Movie No. #62: Close Encounters of the Third Kind added!
---------------------------------------------------
Movie No. #63: City Lights added!
---------------------------------------------------
Movie No. #64: The Apartment added!
---------------------------------------------------
Movie No. #65: The Third Man added!
---------------------------------------------------
Movie No. #66: The Maltese Falcon added!
---------------------------------------------------
Movie No. #67: Network added!
---------------------------------------------------
Movie No. #68: Double Indemnity added!
---------------------------------------------------
Movie No. #69: On the Waterfront added!
---------------------------------------------------
Movie No. #70: The Treasure of the Sierra Madre added!
---------------------------------------------------
Movie No. #71: The French Connection added!
---------------------------------------------------
Movie No. #72: Mr. Smith Goes to Washington added!
---------------------------------------------------
Movie No. #73: West Side Story added!
---------------------------------------------------
Movie No. #74: Bonnie and Clyde added!
---------------------------------------------------
Movie No. #75: Midnight Cowboy added!
---------------------------------------------------
Movie No. #76: A Streetcar Named Desire added!
---------------------------------------------------
Movie No. #77: High Noon added!
---------------------------------------------------
Movie No. #78: It Happened One Night added!
---------------------------------------------------
Movie No. #79: Patton added!
---------------------------------------------------
Movie No. #80: My Fair Lady added!
---------------------------------------------------
Movie No. #81: The Grapes of Wrath added!
---------------------------------------------------
Movie No. #82: Rebel Without a Cause added!
---------------------------------------------------
Movie No. #83: American Graffiti added!
---------------------------------------------------
Movie No. #84: The Searchers added!
---------------------------------------------------
Movie No. #85: The African Queen added!
---------------------------------------------------
Movie No. #86: Doctor Zhivago added!
---------------------------------------------------
Movie No. #87: The Philadelphia Story added!
---------------------------------------------------
Movie No. #88: The Best Years of Our Lives added!
---------------------------------------------------
Movie No. #89: All Quiet on the Western Front added!
---------------------------------------------------
Movie No. #90: Terms of Endearment added!
---------------------------------------------------
Movie No. #91: Stagecoach added!
---------------------------------------------------
Movie No. #92: From Here to Eternity added!
---------------------------------------------------
Movie No. #93: Shane added!
---------------------------------------------------
Movie No. #94: Giant added!
---------------------------------------------------
Movie No. #95: An American in Paris added!
---------------------------------------------------
Movie No. #96: Nashville added!
---------------------------------------------------
Movie No. #97: Mutiny on the Bounty added!
---------------------------------------------------
Movie No. #98: A Place in the Sun added!
---------------------------------------------------
Movie No. #99: Wuthering Heights added!
---------------------------------------------------
Movie No. #100: Yankee Doodle Dandy added!
---------------------------------------------------

---------------------------------------------------
	Sleeping
	Sleep For 22sec
	Go to the page: 1
---------------------------------------------------

In [54]:
prods_index=list(range(0,100))
header = {"user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/12.0"}

for i in urls:
    url2 =i
    imdb2 = requests.get(url = url2, headers = header)
    
    #Writing each movie page into a seperate html file and storing it into the local
    with open(f"movie_{urls.index(i)}.html", 'wb') as imdbmovies_html:
        imdbmovies_html.write(imdb2.content)

    print(f"movie_no {urls.index(i)} scraped.")
    time.sleep(5)

movie_no 0 scraped.
movie_no 1 scraped.
movie_no 2 scraped.
movie_no 3 scraped.
movie_no 4 scraped.
movie_no 5 scraped.
movie_no 6 scraped.
movie_no 7 scraped.
movie_no 8 scraped.
movie_no 9 scraped.
movie_no 10 scraped.
movie_no 11 scraped.
movie_no 12 scraped.
movie_no 13 scraped.
movie_no 14 scraped.
movie_no 15 scraped.
movie_no 16 scraped.
movie_no 17 scraped.
movie_no 18 scraped.
movie_no 19 scraped.
movie_no 20 scraped.
movie_no 21 scraped.
movie_no 22 scraped.
movie_no 23 scraped.
movie_no 24 scraped.
movie_no 25 scraped.
movie_no 26 scraped.
movie_no 27 scraped.
movie_no 28 scraped.
movie_no 29 scraped.
movie_no 30 scraped.
movie_no 31 scraped.
movie_no 32 scraped.
movie_no 33 scraped.
movie_no 34 scraped.
movie_no 35 scraped.
movie_no 36 scraped.
movie_no 37 scraped.
movie_no 38 scraped.
movie_no 39 scraped.
movie_no 40 scraped.
movie_no 41 scraped.
movie_no 42 scraped.
movie_no 43 scraped.
movie_no 44 scraped.
movie_no 45 scraped.
movie_no 46 scraped.
movie_no 47 scraped.
movie_no 48 scraped.
movie_no 49 scraped.
movie_no 50 scraped.
movie_no 51 scraped.
movie_no 52 scraped.
movie_no 53 scraped.
movie_no 54 scraped.
movie_no 55 scraped.
movie_no 56 scraped.
movie_no 57 scraped.
movie_no 58 scraped.
movie_no 59 scraped.
movie_no 60 scraped.
movie_no 61 scraped.
movie_no 62 scraped.
movie_no 63 scraped.
movie_no 64 scraped.
movie_no 65 scraped.
movie_no 66 scraped.
movie_no 67 scraped.
movie_no 68 scraped.
movie_no 69 scraped.
movie_no 70 scraped.
movie_no 71 scraped.
movie_no 72 scraped.
movie_no 73 scraped.
movie_no 74 scraped.
movie_no 75 scraped.
movie_no 76 scraped.
movie_no 77 scraped.
movie_no 78 scraped.
movie_no 79 scraped.
movie_no 80 scraped.
movie_no 81 scraped.
movie_no 82 scraped.
movie_no 83 scraped.
movie_no 84 scraped.
movie_no 85 scraped.
movie_no 86 scraped.
movie_no 87 scraped.
movie_no 88 scraped.
movie_no 89 scraped.
movie_no 90 scraped.
movie_no 91 scraped.
movie_no 92 scraped.
movie_no 93 scraped.
movie_no 94 scraped.
movie_no 95 scraped.
movie_no 96 scraped.
movie_no 97 scraped.
movie_no 98 scraped.
movie_no 99 scraped.

In [18]:
movies =[]
budget1 = []
gross_uscanada1=[]
opening_weekend_uscanada1 = []
gross_worldwide1 = []

for i in urls:

    #Reading each html file created above for each shop
    with open(f"movie_{urls.index(i)}.html", encoding="utf8") as file:
        contents = file.read()
        
    #Parsing the html files
    soup = BeautifulSoup(contents,'lxml')
    rank = urls.index(i) + 1
    movie_name = soup.find('h1').text
    movies.append(movie_name)
    
    #Selecting a class in order to check for the required parameters present inside this class
    xz = soup.findAll("section",{"data-testid":"BoxOffice"})
    
    for money in xz:
        finance = money.find_all("div",{"class":"ipc-metadata-list-item__content-container"})
        
        #Obtaining and saving each movie's overall budget info
        try: 
            budget = finance[0].find("span",{"class":"ipc-metadata-list-item__list-content-item"}).text
        except:
            pass
        budget1.append(budget)

        #Obtaining and saving each movie's gross earning from US & Canada alone
        try:
            gross_uscanada = finance[1].find("span",{"class":"ipc-metadata-list-item__list-content-item"}).text
        except:
            pass
        gross_uscanada1.append(gross_uscanada)
        
        #Obtaining and saving each movie's gross earning from US & Canada on the opening weekend alone
        try:
            opening_weekend_uscanada = finance[2].find("span",{"class":"ipc-metadata-list-item__list-content-item"}).text
        except:
            pass
        opening_weekend_uscanada1.append(opening_weekend_uscanada)
        
        #Obtaining and saving each movie's gross earning worldwide
        try:
            gross_worldwide = finance[3].find("span",{"class":"ipc-metadata-list-item__list-content-item"}).text
        except:
            pass
        gross_worldwide1.append(gross_worldwide)
        
keys = ['Movie','Budget','Gross US & Canada','Opening Weekend US & Canada','Gross worldwide']
values = [movie_name,budget1,gross_uscanada1,opening_weekend_uscanada1,gross_worldwide1]

data_frame1 = pd.DataFrame({
    "Movie": movies,
    "Budget":budget1,
    "Gross US & Canada": gross_uscanada1,
    "Opening Weekend US & Canada": opening_weekend_uscanada1,
    "Gross worldwide": gross_worldwide1,
})

In [19]:
#Joining the dataframes (1st having the details of each movie and 2nd aving the financials of each movie)
final = pd.merge(data_frame,data_frame1,left_on=['Name'],right_on=['Movie'])  
final.head()

,Name,Genre,Year,Duration,User Ratings,Critic Score,Vote,Gross,URL,Movie,Budget,Gross US & Canada,Opening Weekend US & Canada,Gross worldwide
0,The Shawshank Redemption,Drama,(1994),142 min,9.3,81,"2,558,662","28,341,469",https://www.imdb.com/title/tt0111161/,The Shawshank Redemption,"$25,000,000 (estimated)","$28,767,189","$727,327","$28,884,504"
1,Forrest Gump,"Drama, Romance",(1994),142 min,8.8,82,"1,974,472","330,252,182",https://www.imdb.com/title/tt0109830/,Forrest Gump,"$55,000,000 (estimated)","$330,455,270","$24,450,602","$678,226,133"
2,Pulp Fiction,"Crime, Drama",(1994),154 min,8.9,94,"1,966,074","107,928,762",https://www.imdb.com/title/tt0110912/,Pulp Fiction,"$8,000,000 (estimated)","$107,928,762","$9,311,882","$213,928,762"
3,The Lord of the Rings: The Return of the King,"Action, Adventure, Drama",(2003),201 min,9,94,"1,762,356","377,845,905",https://www.imdb.com/title/tt0167260/,The Lord of the Rings: The Return of the King,"$94,000,000 (estimated)","$378,251,207","$72,629,713","$1,146,436,214"
4,The Godfather,"Crime, Drama",(1972),175 min,9.2,100,"1,761,404","134,966,411",https://www.imdb.com/title/tt0068646/,The Godfather,"$6,000,000 (estimated)","$136,166,374","$302,393","$249,825,260"

In [21]:
#Reading the above dataset to check how the features are displaying properly
df = pd.read_csv("C:/Users/prath/Downloads/Movies_updated_final.csv")
df.head()

,Unnamed: 0,Name,Genre,Year,Duration,User Ratings,Critic Score,Vote,Gross,URL,Movie,Budget,Gross US & Canada,Opening Weekend US & Canada,Gross worldwide
0,0,The Shawshank Redemption,Drama,(1994),142 min,9.3,81,"2,558,662","28,341,469",https://www.imdb.com/title/tt0111161/,The Shawshank Redemption,"$25,000,000 (estimated)","$28,767,189","$727,327","$28,884,504"
1,1,Forrest Gump,"Drama, Romance",(1994),142 min,8.8,82,"1,974,472","330,252,182",https://www.imdb.com/title/tt0109830/,Forrest Gump,"$55,000,000 (estimated)","$330,455,270","$24,450,602","$678,226,133"
2,2,Pulp Fiction,"Crime, Drama",(1994),154 min,8.9,94,"1,966,074","107,928,762",https://www.imdb.com/title/tt0110912/,Pulp Fiction,"$8,000,000 (estimated)","$107,928,762","$9,311,882","$213,928,762"
3,3,The Lord of the Rings: The Return of the King,"Action, Adventure, Drama",(2003),201 min,9.0,94,"1,762,356","377,845,905",https://www.imdb.com/title/tt0167260/,The Lord of the Rings: The Return of the King,"$94,000,000 (estimated)","$378,251,207","$72,629,713","$1,146,436,214"
4,4,The Godfather,"Crime, Drama",(1972),175 min,9.2,100,"1,761,404","134,966,411",https://www.imdb.com/title/tt0068646/,The Godfather,"$6,000,000 (estimated)","$136,166,374","$302,393","$249,825,260"

In [23]:
#Converting the critic score into the scale of 10 for easy comparison with user ratings
df['Critic Score'].unique()

array([ 81,  82,  94, 100,  67,  85,  91,  90,  61,  75,  68,  84,  70,
        77,  96,  97,  87,  65,  89,  92,  88,  86,  98,  83,  72,  99,
        63,   0,  66,  95,  73,  79,  69,  93,  80,  76], dtype=int64)

In [24]:
df['Critic Score'] = df['Critic Score'].astype(int)

In [25]:
df['Critic Score'] = df['Critic Score']*10/100

In [26]:
df.head()

,Unnamed: 0,Name,Genre,Year,Duration,User Ratings,Critic Score,Vote,Gross,URL,Movie,Budget,Gross US & Canada,Opening Weekend US & Canada,Gross worldwide
0,0,The Shawshank Redemption,Drama,(1994),142 min,9.3,8.1,"2,558,662","28,341,469",https://www.imdb.com/title/tt0111161/,The Shawshank Redemption,"$25,000,000 (estimated)","$28,767,189","$727,327","$28,884,504"
1,1,Forrest Gump,"Drama, Romance",(1994),142 min,8.8,8.2,"1,974,472","330,252,182",https://www.imdb.com/title/tt0109830/,Forrest Gump,"$55,000,000 (estimated)","$330,455,270","$24,450,602","$678,226,133"
2,2,Pulp Fiction,"Crime, Drama",(1994),154 min,8.9,9.4,"1,966,074","107,928,762",https://www.imdb.com/title/tt0110912/,Pulp Fiction,"$8,000,000 (estimated)","$107,928,762","$9,311,882","$213,928,762"
3,3,The Lord of the Rings: The Return of the King,"Action, Adventure, Drama",(2003),201 min,9.0,9.4,"1,762,356","377,845,905",https://www.imdb.com/title/tt0167260/,The Lord of the Rings: The Return of the King,"$94,000,000 (estimated)","$378,251,207","$72,629,713","$1,146,436,214"
4,4,The Godfather,"Crime, Drama",(1972),175 min,9.2,10.0,"1,761,404","134,966,411",https://www.imdb.com/title/tt0068646/,The Godfather,"$6,000,000 (estimated)","$136,166,374","$302,393","$249,825,260"

In [27]:
#Dropping the index column and the movie column which was repeated after joining
df.drop(['Unnamed: 0','Movie'],axis=1)

,Name,Genre,Year,Duration,User Ratings,Critic Score,Vote,Gross,URL,Budget,Gross US & Canada,Opening Weekend US & Canada,Gross worldwide
0,The Shawshank Redemption,Drama,(1994),142 min,9.3,8.1,"2,558,662","28,341,469",https://www.imdb.com/title/tt0111161/,"$25,000,000 (estimated)","$28,767,189","$727,327","$28,884,504"
1,Forrest Gump,"Drama, Romance",(1994),142 min,8.8,8.2,"1,974,472","330,252,182",https://www.imdb.com/title/tt0109830/,"$55,000,000 (estimated)","$330,455,270","$24,450,602","$678,226,133"
2,Pulp Fiction,"Crime, Drama",(1994),154 min,8.9,9.4,"1,966,074","107,928,762",https://www.imdb.com/title/tt0110912/,"$8,000,000 (estimated)","$107,928,762","$9,311,882","$213,928,762"
3,The Lord of the Rings: The Return of the King,"Action, Adventure, Drama",(2003),201 min,9.0,9.4,"1,762,356","377,845,905",https://www.imdb.com/title/tt0167260/,"$94,000,000 (estimated)","$378,251,207","$72,629,713","$1,146,436,214"
4,The Godfather,"Crime, Drama",(1972),175 min,9.2,10.0,"1,761,404","134,966,411",https://www.imdb.com/title/tt0068646/,"$6,000,000 (estimated)","$136,166,374","$302,393","$249,825,260"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Nashville,"Comedy, Drama, Music",(1975),160 min,7.7,9.6,"25,831","14,824,000",https://www.imdb.com/title/tt0073440/,"$2,200,000 (estimated)","$9,984,123","$9,991,258","$272,619"
96,Mutiny on the Bounty,"Adventure, Biography, Drama",(1935),132 min,7.7,8.7,"22,489","14,824,000",https://www.imdb.com/title/tt0026752/,"$1,950,000 (estimated)","$9,984,123","$9,991,258","$272,619"
97,A Place in the Sun,"Drama, Romance",(1951),122 min,7.8,7.6,"22,199","14,824,000",https://www.imdb.com/title/tt0043924/,"$2,295,304 (estimated)","$9,984,123","$9,991,258","$272,619"
98,Wuthering Heights,"Drama, Romance",(1939),104 min,7.6,0.0,"17,831","762,484",https://www.imdb.com/title/tt0032145/,"$624,643","$15,493","$624,643","$272,619"
99,Yankee Doodle Dandy,"Biography, Drama, Family",(1942),126 min,7.6,8.9,"15,306","11,800,000",https://www.imdb.com/title/tt0035575/,"$11,800,000","$15,493","$624,643","$272,619"

In [28]:
#Saving the obtained dataset as a csv file
df.to_csv('MoviesIMDB_updated.csv')

In [29]:
## create a MongoDB collection 
from pymongo import MongoClient
import json
import pandas as pd

client = MongoClient('mongodb://localhost:27017/')
data = client["imdb"]
imdb_collection = data["imdb_collection"]
imdb_collection.insert_many(data_frame.to_dict('records'))

In [30]:
# create query that shows movie names and user ratings where the rating is greater than or equal to 9 
# Requires pymongo 3.6.0+
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false")
database = client["imdb"]
collection = database["imdb_collection"]

# Created with Studio 3T, the IDE for MongoDB - https://studio3t.com/

query = {}
query["Rating"] = {
    u"$gte": u"9"
}


projection = {}
projection["Name"] = 1.0
projection["Rating"] = 1.0

sort = [ (u"Rating", -1) ]

cursor = collection.find(query, projection = projection, sort = sort)
try:
    for doc in cursor:
        print(doc)
finally:
    client.close()

{'_id': ObjectId('622f8cfb219f311b4e1f1b42'), 'Name': 'The Shawshank Redemption', 'Rating': '9.3'}
{'_id': ObjectId('622f8cfb219f311b4e1f1b46'), 'Name': 'The Godfather', 'Rating': '9.2'}
{'_id': ObjectId('622f8cfb219f311b4e1f1b45'), 'Name': 'The Lord of the Rings: The Return of the King', 'Rating': '9'}
{'_id': ObjectId('622f8cfb219f311b4e1f1b4b'), 'Name': "Schindler's List", 'Rating': '9'}
{'_id': ObjectId('622f8cfb219f311b4e1f1b4d'), 'Name': 'The Godfather: Part II', 'Rating': '9'}
{'_id': ObjectId('622f8cfb219f311b4e1f1b58'), 'Name': '12 Angry Men', 'Rating': '9'}